### ISSUE TITLE
Uncaught Error: Cannot find module "react/lib/ReactComponentTreeHook"

### ISSUE THREAD

**Issue by dgsunesen** [jmarceli/redux-elm-boilerplate#2]
Building this project gives me the following error:

`Uncaught Error: Cannot find module "react/lib/ReactComponentTreeHook"`

This results in a blank window.

**Comment by dgsunesen** [comment]
Does anyone have a solution to this?

**Comment by dgsunesen** [comment]
Seems like the version of `react` in this project is not compatible with the version of `react-dom`. React does not contain `ReactComponentTreeHook` at all.

**Comment by dgsunesen** [comment]
To be more clear: It builds as it should, but when I open up the browser I see that error.

**Comment by jmarceli** [comment]
Hi. Sorry for the delay. I think I manage to fix your issue. Please pull latest commit and check if it works now. The `react-dom` version should be fixed at `15.0.1`.

**Comment by dgsunesen** [comment]
Yessir it works! Perfect! Thanks a lot!

**Comment by jmarceli** [comment]
OK. Thanks for reporting this bug.

I should probably update `react` and `react-dom` versions but ATM I have no spare time to do this.
